# Generated by Django 4.0.3 on 2022-03-13 21:46

import api_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.UUIDField(default=api_service.models.uuid_with_20, editable=False, primary_key=True, serialize=False),
        ),
    ]
