# Generated by Django 4.0.3 on 2022-03-13 21:48

import api_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0002_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default=api_service.models.uuid_with_20, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
